version: 2
# TODO? Use registries if you need to authenticate to a package registry.
# For example when using private GitHub packages, change & uncomment lines below.
#
#registries:
#  mvn-repo:
#    type: maven-repository
#    url: https://maven.pkg.github.com/navikt/backend-golden-path
#    username: username
#    password: ${{secrets.READER_TOKEN}}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    # see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#example-3-individual-pull-requests-for-major-updates-and-grouped-for-minorpatch-updates
    groups:
      github-actions-bump:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"


  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
#    registries:
#      - mvn-repo
    groups:
      gradle-bump:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    groups:
      docker-bump:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
