apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mangfold-backend
  namespace: heda
spec:
  env:
    - name: BIGQUERY_PROJECT_ID
      value: "heda-prod-2664"

  gcp:
    bigQueryDatasets:
      - name: hr_data
        permission: READ
      - name: mangfold_processed_data
        permission: READ

  ingresses:
    - https://mangfold-backend.intern.dev.nav.no
    - https://mangfold-backend.intern.nav.no #Kan velge å bytte intern til ansatt slik at alle ansatte får åpnet
  image: {{image}}
  port: 8080
  replicas:
    max: 2
    min: 1
  resources:
    requests:
      cpu: 66m
      memory: 160Mi
    limits:
      memory: 255Mi

  observability:
    logging:
      destinations:
        - id: loki
