apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mangfold-backend  # TODO: Change this name to your application name
  namespace: heda # TODO: Change this to your team's namespace
spec:
  env: 
    - name: BIGQUERY_PROJECT_ID
      value: "heda-prod-2664"

  gcp:
    serviceAccount:
      email: heda-1c0e@knada-gcp.iam.gserviceaccount.com
    bigQueryDatasets:
      - name: hr_data
        permission: READ

  ingresses:
    - https://mangfold-backend.intern.dev.nav.no
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  observability:
    logging:
      destinations:
        - id: loki