name: Automerge Dependabot PRs

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@main
        with:
          token: ${{ github.token }}
          minimum-age-of-pr: '3'
          blackout-periods: '2025-07-01/2025-07-31,2025-12-15/2026-01-02' # TODO: Update periods suitable for your team, or omit this field entirely
