name: Run test & build on PRs
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  test-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high # Fail if introducing high or critical vulnerabilities
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
      - name: Test & build
        run: ./gradlew test build
